LUX71 -  create login homepage pin
Bug-BustersPRO/luxiergerie-back pull request #11
Opened 2024-03-21 11:14 UTC by maxime-auneau

2024-03-21 13:32 UTC, JocelynDeloose requested changes

2024-03-21 13:32 UTC, JocelynDeloose commented on src/main/java/com/luxiergerie/Controllers/ClientController.java
> +    }
this.clientRepository.findAll().stream()
                                              .map(ClientMapper::toDTO)
                                             .collect(Collectors.toList()) ici enlever le static

2024-03-21 13:32 UTC, JocelynDeloose commented on src/main/java/com/luxiergerie/Controllers/ClientController.java
> +        Client savedClient = this.clientRepository.save(client);
optional

2024-03-21 13:32 UTC, JocelynDeloose commented on src/main/java/com/luxiergerie/Controllers/ClientController.java
> +        if (role == null) {
revoir la syntaxe !!

2024-03-21 13:32 UTC, JocelynDeloose commented on src/main/java/com/luxiergerie/Controllers/ClientController.java
> +        if (client == null) {
la même

2024-03-21 13:32 UTC, JocelynDeloose commented on src/main/java/com/luxiergerie/Controllers/ClientController.java
> +        if (client.getRoom() != null) {
isNotNull?

2024-03-21 13:32 UTC, JocelynDeloose commented on src/main/java/com/luxiergerie/Controllers/RoomController.java
> +        return this.roomRepository.findAllRoomByClientIsNull();
findAllEmptyRoom?

2024-03-21 13:32 UTC, JocelynDeloose commented on src/main/java/com/luxiergerie/Controllers/RoomController.java
> +        if (existingRole == null) {
même chose que clientController

2024-03-21 13:32 UTC, JocelynDeloose commented on src/main/java/com/luxiergerie/Controllers/RoomController.java
> +        startRoomNumber = Math.max(startRoomNumber, maxRoomNumber + 1);
même chose que pour clientController hésites pas à mettre à la ligne pour la lisibilité

2024-03-21 13:32 UTC, JocelynDeloose commented on src/main/java/com/luxiergerie/Controllers/RoomController.java
> +            roomDto.setRoleName(roomDto.getRoleName());
un buider?

2024-03-21 13:32 UTC, JocelynDeloose commented on src/main/java/com/luxiergerie/Controllers/RoomController.java
> +        Role role = this.roleRepository.findByName(roomDTO.getRoleName());
Optional?

2024-03-21 13:32 UTC, JocelynDeloose commented on src/main/java/com/luxiergerie/Domain/Mapper/ClientMapper.java
> +        return dto;
revoir le nommage c'est pas super clair du coup ;)

2024-03-21 13:32 UTC, JocelynDeloose commented on src/main/java/com/luxiergerie/Domain/Repository/RoomRepository.java
> +    public List<Room> findAllRoomByClientIsNull();
espace entre 14 et 15 :)

2024-03-21 13:40 UTC, mohamedehn approved these changes
good for me

2024-03-22 13:25 UTC, emmirose approved these changes
Belle démo !

2024-03-22 13:29 UTC, KevinRoig approved these changes

2024-03-22 13:40 UTC, maxime-auneau reviewed
Done

2024-03-22 13:49 UTC, JocelynDeloose approved these changes
nice

2024-03-22 13:49 UTC, merged