Lux110 config hotel
Bug-BustersPRO/luxiergerie-back pull request #33
Opened 2024-06-11 14:04 UTC by mohamedehn

2024-06-11 14:13 UTC, JocelynDeloose requested changes

2024-06-11 14:13 UTC, JocelynDeloose commented on src/main/java/com/luxiergerie/Controllers/HotelController.java
> +            if (name != null) {
isNotNull???

2024-06-11 14:13 UTC, JocelynDeloose commented on src/main/java/com/luxiergerie/Controllers/HotelController.java
> +            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
import static

2024-06-11 14:13 UTC, JocelynDeloose commented on src/main/java/com/luxiergerie/Controllers/HotelController.java
> +            return new ResponseEntity<>(MappedHotelFrom(updatedHotel), HttpStatus.OK);
import static

2024-06-11 14:13 UTC, JocelynDeloose commented on src/main/java/com/luxiergerie/Controllers/HotelController.java
> +                    return new ResponseEntity<>(HttpStatus.BAD_REQUEST);
import static

2024-06-11 14:13 UTC, JocelynDeloose commented on src/main/java/com/luxiergerie/Controllers/HotelController.java
> +            if (colors != null) {
isNotNull

2024-06-11 14:13 UTC, JocelynDeloose commented on src/main/java/com/luxiergerie/Controllers/HotelController.java
> +        if (!hotels.isEmpty()) {
isBlank?

2024-06-11 14:13 UTC, JocelynDeloose commented on src/main/java/com/luxiergerie/Controllers/HotelController.java
> +            return new ResponseEntity<>(HttpStatus.CONFLICT);
static ( j'arrete de le noter mais c'est pour tout tes HttpStatus)

2024-06-11 14:13 UTC, JocelynDeloose commented on src/main/java/com/luxiergerie/Domain/Entity/Hotel.java
> +
ligne vide

2024-06-11 14:40 UTC, JocelynDeloose approved these changes
Nice

2024-06-12 12:34 UTC, maxime-auneau approved these changes

2024-06-12 12:34 UTC, merged