Lux 128
Bug-BustersPRO/luxiergerie-back pull request #46
Opened 2024-07-22 14:32 UTC by emmirose

2024-07-22 15:34 UTC, JocelynDeloose requested changes

2024-07-22 15:34 UTC, JocelynDeloose commented on src/main/java/com/luxiergerie/Controllers/PurchaseController.java
> +    if(purchaseDTO.getId() != null) {
Object ... isNotNull()

2024-07-22 15:34 UTC, JocelynDeloose commented on src/main/java/com/luxiergerie/Controllers/PurchaseController.java
>    }
espace

2024-07-22 15:34 UTC, JocelynDeloose commented on src/main/java/com/luxiergerie/Domain/Entity/Client.java
> +      if (this.authorities == null) {
isNull

2024-07-23 09:32 UTC, JocelynDeloose approved these changes

2024-07-23 10:05 UTC, mohamedehn approved these changes
Good job

2024-07-23 10:05 UTC, merged